name: Test and Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-build:
    runs-on: macos-latest
    name: Test and Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Cocoapods
        run: sudo gem install cocoapods

      - name: Install Dependencies
        run: npm install

            - name: Install Pods 
        working-directory: ./ios
        run: pod install

      - name: Run Tests
        run: npm test

      - name: Build iOS
        run: npm run ios
          
